config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  resources :users

  get "/sign_up" => "users#new", as: "sign_up"
  get "/sign_in" => "sessions#new", as: "sign_in"
  post "/sign_in" => "sessions#create", as:"signed_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect to the user's show page.

        sign_in user
        redirect_to user
      else
        # Create an error message.
        flash[:danger] = 'Invalid email/password combination' # Fix this
        render 'new'

      end
  end

  def destroy
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
    
      redirect_to sign_in
      byebug
    else
      render 'new'
    end
    #add sessions if logged in
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    #redirect to show page
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
       @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
  
  def sign_out
   
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skincare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  Name: <br />
  <%= f.text_field :username %> <br />
  Email: <br />
  <%= f.text_field :email %> <br />
  Password: <br />
  <%= f.password_field :password %> <br />
  
 

 <%= f.submit "Submit" %>

<% end %>

app/views/users/edit.html.erb
<div class="col-md-6 mx-auto mt-5">
  <div class="card mt-3 mx-3 p-1 d-flex align-items-center">
    <div class="card-body">
      <h1 class="card-title text-dark text-center">Edit your profile</h1></a>
        <br />
        <br />
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-md-6 mx-auto mt-5">
  <div class="card mt-3 mx-3 p-1 d-flex align-items-center">
    <div class="card-body">
      <h1 class="card-title text-dark text-center">Sign up here!</h1></a>
        <br />
        <br />
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome to your page,<%= current_user.username %>!</h1>

 <% if logged_in? %>
         
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_path %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", sign_in_path %></li>
        <% end %>

app/views/welcome/index.html.erb
<div class="jumbotron vertical-center">
  <div class="container text-center">
    <h1>Welcome to your personal skincare routine tracker!</h1>
    <p class="lead">Keep track of your skincare routine!</p>
    <hr class="my-4">

    <%# if current_user %>
      <h2> Welcome back! </h2>
    <%# else %>
      <a href="/sign_up" class="btn btn-dark mb-2 sr-icons">Sign Up</a>
      <a href="/sign_in" class="btn btn-dark mb-2 sr-icons">Sign In</a>
    <%#end %>
    </p>
  </div>
</div>